# fly.toml app configuration file generated for trumpbot on 2023-10-13T11:23:02-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "trumpbot"
primary_region = "lax"

[build]
